app :
	uvicorn $@:app --host 0.0.0.0 --port 3500 --reload

app01 :
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload

api :
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload

api2 :
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload

main : 
	uvicorn $@:app --host 0.0.0.0 --port 3000 --reload
